# Generated by Django 2.0 on 2018-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=32, null=True)),
                ('parent_guid', models.CharField(blank=True, max_length=32, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=128, null=True)),
                ('category_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=32, null=True)),
                ('ypmc', models.CharField(blank=True, max_length=128, null=True)),
                ('tymc', models.CharField(blank=True, max_length=128, null=True)),
                ('ppmc', models.CharField(blank=True, max_length=128, null=True)),
                ('jx', models.CharField(blank=True, max_length=128, null=True)),
                ('zycf', models.TextField(blank=True, null=True)),
                ('gnzz', models.CharField(blank=True, max_length=1024, null=True)),
                ('yfyl', models.TextField(blank=True, null=True)),
                ('blfy', models.TextField(blank=True, null=True)),
                ('jj', models.TextField(blank=True, null=True)),
                ('zysx', models.TextField(blank=True, null=True)),
                ('ywxhzy', models.TextField(blank=True, null=True)),
                ('cc', models.CharField(blank=True, max_length=128, null=True)),
                ('yxq', models.CharField(blank=True, max_length=128, null=True)),
                ('sccs', models.CharField(blank=True, max_length=128, null=True)),
                ('pzwh', models.CharField(blank=True, max_length=128, null=True)),
                ('jgqj', models.CharField(blank=True, max_length=128, null=True)),
                ('yptp', models.CharField(blank=True, max_length=128, null=True)),
                ('is_otc', models.CharField(blank=True, max_length=1, null=True)),
                ('c1_guid', models.CharField(blank=True, max_length=32, null=True)),
                ('c1_name', models.CharField(blank=True, max_length=128, null=True)),
                ('c2_guid', models.CharField(blank=True, max_length=32, null=True)),
                ('c2_name', models.CharField(blank=True, max_length=128, null=True)),
                ('xingzhuang', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
    ]
